name:                stmlearning
version:             0.1.0.0
github:              "sandoichi/stmlearning"
license:             BSD3
author:              "sandoichi"
maintainer:          ""
copyright:           "2019 Sandoichi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/stmlearning#readme>

dependencies:
- base >= 4.7 && < 5
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - async
  - stm
  - stm-chans
  - random
  - containers

executables:
  stmlearning-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stmlearning
